import os
import sys

Import("env")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags
# tweak this if you want to use different folders, or more folders, to store your source code in.

def link_framework(framework_path, framework_name, header_path=""):
    # Add the framework to scons
    env.Append(LINKFLAGS=[
        "-F" + framework_path,
        "-framework", framework_name
    ])

    if header_path == "": return

    # Add the header path to the Objective-C++ compiler
    env.Append(CPPPATH=["-F" + header_path])
    env.Append(CXXFLAGS=["-F" + header_path])

Import("sources")

env.Append(CPPPATH=["/"])
sources += Glob("*.cpp")
sources += Glob("*.mm")

env.Append(LINKFLAGS="-framework Foundation")
env.Append(LINKFLAGS="-framework GameController")