import os
import sys

Import("env")

match env["platform"]:
    case "android":
        env.add_sub_build("platform/android")
    case "ios":
        env.add_sub_build("platform/ios")
    case "linux":
        env.add_sub_build("platform/linux")
    case "macos":
        env.add_sub_build("platform/macos")
    case "windows":
        env.add_sub_build("platform/windows")